name: Namespace Cloud Cache
description: Persist cache between job executions on Namespace Cloud
author: https://namespace.so/
requirements: []
configuration:
  properties:
    paths:
      type: [string, array]
    symlink:
      type: boolean
  additionalProperties: false
